In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('data.csv')
dataset

date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
...                   ...           ...       ...        ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0         7912     1.5           0     0          3        1340   
1         9050     2.0           0     4          5        3370   
2        11947     1.0           0     0          4        1930   
3         8030     1.0           0     0          4        1000   
4        10500     1.0           0     0          4        1140   
...        ...     ...         ...   ...        ...         ...   
4595      6360     1.0           0     0          4        1510   
4596      7573     2.0           0     0          3        1460   
4597      7014     2.0           0     0          3        3010   
4598      6630     1.0           0     0          3        1070   
4599      8102     2.0           0     0          4        1490   

      sqft_basement  yr_built  yr_renovated                    street  \
0                 0      1955          2005      18810 Densmore Ave N   
1               280      1921             0           709 W Blaine St   
2                 0      1966             0  26206-26214 143rd Ave SE   
3              1000      1963             0           857 170th Pl NE   
4               800      1976          1992         9105 170th Ave NE   
...             ...       ...           ...                       ...   
4595              0      1954          1979            501 N 143rd St   
4596              0      1983          2009          14855 SE 10th Pl   
4597              0      2009             0          759 Ilwaco Pl NE   
4598           1020      1974             0         5148 S Creston St   
4599              0      1990             0         18717 SE 258th St   

           city  statezip country  
0     Shoreline  WA 98133     USA  
1       Seattle  WA 98119     USA  
2          Kent  WA 98042     USA  
3      Bellevue  WA 98008     USA  
4       Redmond  WA 98052     USA  
...         ...       ...     ...  
4595    Seattle  WA 98133     USA  
4596   Bellevue  WA 98007     USA  
4597     Renton  WA 98059     USA  
4598    Seattle  WA 98178     USA  
4599  Covington  WA 98042     USA  

[4600 rows x 18 columns]

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           4600 non-null   object 
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64  
 5   sqft_lot       4600 non-null   int64  
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64  
 8   view           4600 non-null   int64  
 9   condition      4600 non-null   int64  
 10  sqft_above     4600 non-null   int64  
 11  sqft_basement  4600 non-null   int64  
 12  yr_built       4600 non-null   int64  
 13  yr_renovated   4600 non-null   int64  
 14  street         4600 non-null   object 
 15  city           4600 non-null   object 
 16  statezip       4600 non-null   object 
 17  country        4600 non-null   object 
dtypes: float

In [4]:
Dataset = dataset.drop('date', axis=1)

In [5]:
print(Dataset)

             price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0     3.130000e+05       3.0       1.50         1340      7912     1.5   
1     2.384000e+06       5.0       2.50         3650      9050     2.0   
2     3.420000e+05       3.0       2.00         1930     11947     1.0   
3     4.200000e+05       3.0       2.25         2000      8030     1.0   
4     5.500000e+05       4.0       2.50         1940     10500     1.0   
...            ...       ...        ...          ...       ...     ...   
4595  3.081667e+05       3.0       1.75         1510      6360     1.0   
4596  5.343333e+05       3.0       2.50         1460      7573     2.0   
4597  4.169042e+05       3.0       2.50         3010      7014     2.0   
4598  2.034000e+05       4.0       2.00         2090      6630     1.0   
4599  2.206000e+05       3.0       2.50         1490      8102     2.0   

      waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0              0     0          3    

In [6]:
dataset.describe()

price     bedrooms    bathrooms   sqft_living      sqft_lot  \
count  4.600000e+03  4600.000000  4600.000000   4600.000000  4.600000e+03   
mean   5.519630e+05     3.400870     2.160815   2139.346957  1.485252e+04   
std    5.638347e+05     0.908848     0.783781    963.206916  3.588444e+04   
min    0.000000e+00     0.000000     0.000000    370.000000  6.380000e+02   
25%    3.228750e+05     3.000000     1.750000   1460.000000  5.000750e+03   
50%    4.609435e+05     3.000000     2.250000   1980.000000  7.683000e+03   
75%    6.549625e+05     4.000000     2.500000   2620.000000  1.100125e+04   
max    2.659000e+07     9.000000     8.000000  13540.000000  1.074218e+06   

            floors   waterfront         view    condition   sqft_above  \
count  4600.000000  4600.000000  4600.000000  4600.000000  4600.000000   
mean      1.512065     0.007174     0.240652     3.451739  1827.265435   
std       0.538288     0.084404     0.778405     0.677230   862.168977   
min       1.000000     0.000000     0.000000     1.000000   370.000000   
25%       1.000000     0.000000     0.000000     3.000000  1190.000000   
50%       1.500000     0.000000     0.000000     3.000000  1590.000000   
75%       2.000000     0.000000     0.000000     4.000000  2300.000000   
max       3.500000     1.000000     4.000000     5.000000  9410.000000   

       sqft_basement     yr_built  yr_renovated  
count    4600.000000  4600.000000   4600.000000  
mean      312.081522  1970.786304    808.608261  
std       464.137228    29.731848    979.414536  
min         0.000000  1900.000000      0.000000  
25%         0.000000  1951.000000      0.000000  
50%         0.000000  1976.000000      0.000000  
75%       610.000000  1997.000000   1999.000000  
max      4820.000000  2014.000000   2014.000000

In [7]:
Y = dataset.iloc[:, 1].values
print(Y)

[ 313000.       2384000.        342000.       ...  416904.166667
  203400.        220600.      ]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
import numpy as np

# Select categorical and numerical columns
categorical_columns = ['street', 'city', 'statezip', 'country']
numerical_columns = ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 
                     'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated']

# Create a ColumnTransformer to handle both categorical and numerical columns
ct = ColumnTransformer(
    transformers=[
        ('num', SimpleImputer(strategy='mean'), numerical_columns),  # Impute missing numerical data with the mean
        ('cat', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), categorical_columns)  # One-hot encode categorical data
    ],
    remainder='passthrough'  # Keep the remaining columns (e.g., 'price')
)

# Apply the preprocessing
X_preprocessed = ct.fit_transform(Dataset)

# Display the preprocessed data
X_preprocessed[:5]


array([[3.000e+00, 1.500e+00, 1.340e+03, ..., 0.000e+00, 1.000e+00,
        3.130e+05],
       [5.000e+00, 2.500e+00, 3.650e+03, ..., 0.000e+00, 1.000e+00,
        2.384e+06],
       [3.000e+00, 2.000e+00, 1.930e+03, ..., 0.000e+00, 1.000e+00,
        3.420e+05],
       [3.000e+00, 2.250e+00, 2.000e+03, ..., 0.000e+00, 1.000e+00,
        4.200e+05],
       [4.000e+00, 2.500e+00, 1.940e+03, ..., 0.000e+00, 1.000e+00,
        5.500e+05]])

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X_preprocessed, Y, test_size=0.2, random_state=2)

In [10]:
print(x_train)

[[3.0000e+00 1.7500e+00 1.7300e+03 ... 0.0000e+00 1.0000e+00 5.2200e+05]
 [3.0000e+00 1.0000e+00 9.9000e+02 ... 0.0000e+00 1.0000e+00 2.8495e+05]
 [4.0000e+00 2.5000e+00 1.9400e+03 ... 0.0000e+00 1.0000e+00 5.5000e+05]
 ...
 [3.0000e+00 2.0000e+00 1.5100e+03 ... 0.0000e+00 1.0000e+00 3.9750e+05]
 [4.0000e+00 2.0000e+00 1.3500e+03 ... 0.0000e+00 1.0000e+00 2.8879e+05]
 [5.0000e+00 2.5000e+00 2.6400e+03 ... 0.0000e+00 1.0000e+00 6.3250e+05]]


In [11]:
print(y_train)

[522000. 284950. 550000. ... 397500. 288790. 632500.]


In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train= sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [13]:
print(x_train)

[[-0.44312656 -0.51806678 -0.42979851 ... -0.01648675  0.
  -0.06133876]
 [-0.44312656 -1.4866455  -1.22405866 ... -0.01648675  0.
  -0.62188235]
 [ 0.65499178  0.45051193 -0.20440036 ... -0.01648675  0.
   0.00487183]
 ...
 [-0.44312656 -0.19520721 -0.66592991 ... -0.01648675  0.
  -0.35573942]
 [ 0.65499178 -0.19520721 -0.83766183 ... -0.01648675  0.
  -0.61280204]
 [ 1.75311011  0.45051193  0.5469268  ... -0.01648675  0.
   0.19995661]]


In [14]:
print(x_test)

[[-0.44312656 -0.84092636 -0.71959613 ... -0.01648675  0.
  -0.74709131]
 [ 0.65499178 -0.51806678 -0.61226368 ... -0.01648675  0.
  -0.58641239]
 [ 1.75311011  0.45051193  0.22492944 ... -0.01648675  0.
   1.26996706]
 ...
 [-0.44312656 -0.84092636 -0.54786421 ... -0.01648675  0.
  -0.77558551]
 [-0.44312656  0.7733715   0.08539726 ... -0.01648675  0.
  -0.78492593]
 [-0.44312656  0.45051193  0.07466401 ... -0.01648675  0.
   1.30543702]]


In [60]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [20]:
y_pred = regressor.predict(x_test)
print(y_pred)

[ 2.28492937e+05  2.91378499e+05  1.09329431e+06  2.12047075e+05
  5.08867588e+05  3.77504642e+05  5.67500000e+05  6.32854549e+05
  6.45014827e+05  2.78384804e+05  3.40652614e+05  2.87267366e+05
  4.05000000e+05  5.98491998e+05  4.71726713e+05  4.68020393e+05
  6.37822188e+05  3.95589665e+05  8.82267366e+05  5.50039933e+05
  6.98474828e+05  3.27238238e+05  3.48244309e+05  4.91554642e+05
  2.17337431e+05  6.71443450e+05  3.40872853e+05  3.53345238e+05
  1.93492937e+05  4.17639665e+05  2.68020393e+05  5.51247075e+05
  3.44375700e+05  5.21569067e+05  3.95294309e+05  3.05492937e+05
  8.73611699e+05  8.45101488e+04  6.23014827e+05  4.56460135e+05
  6.03121232e+05  6.21201232e+05  1.61492937e+05  7.85069067e+05
  6.73322188e+05  1.16955472e+06  2.70727744e+05  3.63294309e+05
  5.82038475e+05  4.30039933e+05  2.34681136e+05  6.58322188e+05
  9.16146713e+05  7.60491998e+05  1.91046398e+05  7.07218369e+05
  4.07320366e+05  5.12554642e+05  4.43551507e+05  5.97322188e+05
  3.33772853e+05  1.15640

In [42]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)


R² Score: 0.9998524496379376


In [48]:
from sklearn.decomposition import PCA

pca = PCA(0.95)
X_pca = pca.fit_transform(X_preprocessed)
X_pca.shape

(4600, 1)

In [49]:
X_pca

array([[-238984.99169797],
       [1832009.98204174],
       [-209971.28099203],
       ...,
       [-135082.03924876],
       [-348587.82980023],
       [-331383.56298855]])

In [52]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, Y, test_size=0.2, random_state=30)

In [56]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train_pca, y_train)
model.score(X_test_pca, y_test)

0.9999999880661867